In [62]:
import pandas as pd
import numpy as np

In [63]:
df = pd.read_csv('top100songs',sep='\t')

In [64]:
df

,Unnamed: 0,Song’s name,Song’s artist
0,0,Flowers,Miley Cyrus
1,1,Kill Bill,SZA
2,2,Last Night,Morgan Wallen
3,3,Unholy,Sam Smith & Kim Petras
4,4,Creepin',"Metro Boomin, The Weeknd & 21 Savage"
...,...,...,...
95,95,Yandel 150,Yandel & Feid
96,96,Heart To Heart,Mac DeMarco
97,97,Next Thing You Know,Jordan Davis
98,98,Never Gonna Not Dance Again,P!nk
99,99,Open Arms,SZA Featuring Travis Scott

In [65]:
#dropping unwanted column
df = df.drop('Unnamed: 0', axis=1)

In [66]:
df

                    Song’s name                         Song’s artist
0                       Flowers                           Miley Cyrus
1                     Kill Bill                                   SZA
2                    Last Night                         Morgan Wallen
3                        Unholy                Sam Smith & Kim Petras
4                      Creepin'  Metro Boomin, The Weeknd & 21 Savage
..                          ...                                   ...
95                   Yandel 150                         Yandel & Feid
96               Heart To Heart                           Mac DeMarco
97          Next Thing You Know                          Jordan Davis
98  Never Gonna Not Dance Again                                  P!nk
99                    Open Arms            SZA Featuring Travis Scott

[100 rows x 2 columns]

In [67]:
song_list = list(df['Song’s name'])

In [68]:
song_list = [i.lower() for i in song_list]

In [69]:
song_list

['flowers',
 'kill bill',
 'last night',
 'unholy',
 "creepin'",
 'cuff it',
 'anti-hero',
 'die for you',
 "i'm good (blue)",
 'as it was',
 'rich flex',
 'just wanna rock',
 'thought you should know',
 "boy's a liar, pt. 2",
 'made you look',
 'under the influence',
 'golden hour',
 'you proof',
 'rock and a hard place',
 'something in the orange',
 'thank god',
 'bad habit',
 'going, going, gone',
 'escapism',
 'superhero (heroes & villains)',
 'lavender haze',
 'calm down',
 'players',
 'shirt',
 'sure thing',
 'the kind of love we make',
 'heart like a truck',
 'bzrp music sessions, vol. 53',
 'snooze',
 'until i found you',
 'wait for u',
 'i like you (a happier song)',
 'i wrote the book',
 'bebe dame',
 'tomorrow 2',
 'about damn time',
 'wait in the truck',
 'she had me at heads carolina',
 'nobody gets me',
 'what my world spins around',
 'unstoppable',
 'one thing at a time',
 'whiskey on you',
 'dawns',
 'love again',
 'everything i love',
 'lift me up',
 'que vuelvas',
 'low',
 'tennessee orange',
 'x si volvemos',
 'bloody mary',
 'handle on you',
 "what he didn't do",
 'freestyle',
 'wild as her',
 'spin bout u',
 "you didn't",
 "growin' up and gettin' old",
 'nonsense',
 'here with me',
 'the color violet',
 'amg',
 '10:35',
 'la bachata',
 'forget me',
 'shut up my moms calling',
 'blind',
 'omg',
 'no se va',
 'love you better',
 'la jumpa',
 'prc',
 "that's what tequila does",
 'love language',
 'tennessee fan',
 'ditto',
 'watch the world burn',
 'human',
 'in ha mood',
 'back end',
 'do it again',
 'hey mor',
 'too many nights',
 'ghost in the machine',
 'fin de semana',
 'snap',
 'california breeze',
 "i'm not here to make friends",
 'gato de noche',
 'yandel 150',
 'heart to heart',
 'next thing you know',
 'never gonna not dance again',
 'open arms']

In [70]:
import random

In [81]:
def user_choice(df):
    song_list = list(df['Song’s name'])
    song_list = [i.lower() for i in song_list]
    while True:
        user_input = input('Enter your choice of music: ')
        if (user_input.lower() not in song_list):
            print('***************************************************************')
            print('Your choice of song is not in the top 100 hit, try another song')
            print('***************************************************************')
        else:
            choice = df.loc[(df["Song’s name"] == user_input.title()), ["Song’s artist"]]
            choice = choice["Song’s artist"].tolist()
            choice = [x.lower() for x in choice]
            user_input2 = input('more than 1 song has same title, Enter artist name to be specific: ')
            
            if (user_input2.lower() not in choice):
                print(f"Your song choice: '{user_input.title()}' with artist name: '{user_input2.title()}' is not in the Top 100")
                break
            else:
                return random.sample(song_list, k=1)

In [82]:
user_choice(df)

Enter your choice of music: fhh
***************************************************************
Your choice of song is not in the top 100 hit, try another song
***************************************************************
Enter your choice of music: flowers
more than 1 song has same title, Enter artist name to be specific: Miley Cyrus

['do it again']

def ask_input_title(df):
    list_of_songs = list(df['title'].unique())
    list_of_songs = [x.lower() for x in list_of_songs]
    while True:
        prompt = input(f'enter a song title of the Top100: ')
        if (prompt.lower() not in list_of_songs):
            print(f'Your choice is not in the Top100. Try another one :)')
        else:
            options = df.loc[(df['title'] == prompt.title()),['artist']]
            options = options['artist'].tolist()
            options = [x.lower() for x in options]
            clarification = input(f' Your song might be in the list. Please state which artist you are referring to:')
            if (clarification.lower() not in options):
                print(f' Your combination of song title {prompt.title()} and artist {clarification.title()} is not in the Top 100')
                break
            else:
                print('Your Song is in the Top100 List :)')
                return prompt.title()